openapi: 3.0.3
info:
  title: Payments Data Product (GraphQL)
  version: v1
  x-git-sha: d171ad18798898b806c33d7e06a8c49f0779b4fe
servers:
- url: http://127.0.0.1:8000/graphql
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  /graphql:
    post:
      summary: GraphQL endpoint
      operationId: payments_graphql
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                variables:
                  type: object
              required:
              - query
      responses:
        '200':
          description: GraphQL JSON response
          content:
            application/json:
              schema:
                type: object
      x-graphql-operations:
      - name: list_payments
        kind: query
        args: &id001
          limit: Int
          offset: Int
          order_by: '[OrderBy!]'
          where: {}
      - name: list_payments
        kind: query
        args: *id001
      - name: list_bills
        kind: query
        args: &id002
          limit: Int
          offset: Int
          order_by: '[OrderBy!]'
          where: {}
      - name: list_bills
        kind: query
        args: *id002
x-data-product:
  name: payments
  type: graphql
